name: Metrics embed

on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          filename: profile/metrics.svg
          
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_twemoji: yes
          
          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: most-used, recently-used
          plugin_languages_other: true
        
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
